# Server Coin Card ID to do transactions from users to withdraw or deposit coins
ServerCard: "e1301fadfc35"

# Cooldown between player actions in ticks (20 ticks = 1 second)
Cooldown: 20

# Queue interval in milliseconds between each transaction
# Higher values prevent rate limiting but increase wait time
QueueIntervalMs: 1010

# The cash notes list to add or remove notes and their worth
# These will be loaded into notes.dat on first startup
Note List:
  1:
    name: "&e₿ Note"
    item: "PAPER"
    model: 1
    lore:
      1: ""
      2: "&71 SAT"
      3: ""
    worth: "0.00000001"
